version: "3.7"

networks:
  internal:
    driver: "bridge"
  external:
    name: chat-api
    driver: "bridge"

volumes:
  database:
    driver: "local"

services:
  api:
    build: ./api
    networks:
      - internal
      - external
    ports:
      - "${DOCKER_API_PORT:-3000}:3000"
    volumes:
      - ./api:/var/www/api
      - /var/www/api/node_modules
    restart: always

  web:
    build: ./web
    networks:
      - internal
    ports:
      - "${DOCKER_PWA_PORT:-4200}:4200"
    volumes:
      - ./web:/var/www/web
      - /var/www/web/node_modules
    restart: always

  mongo:
    image: mongo
    networks:
      - internal
    ports:
      - "${DOCKER_MONGO_PORT:-27017}:27017"
    volumes:
      - database:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DOCKER_MONGO_INITDB_DATABASE:-chat}
      MONGO_INITDB_USERNAME: ${DOCKER_MONGO_INITDB_USERNAME:-admin}
      MONGO_INITDB_PASSWORD: ${DOCKER_MONGO_INITDB_PASSWORD:-secret}
      MONGO_INITDB_ROLE: ${DOCKER_MONGO_INITDB_ROLE:-readWrite}

